### ISSUE TITLE
full-functioning dashboard

### ISSUE THREAD

**Issue by nervouna** [nervouna/Campaign-Tracker#2]
- [x] authentication #3
- [x] ui #6 
- [x] list of short links #8 
- [ ] list of campaigns #9 
- [ ] list of visits #10 
- [ ] statistics
